### ISSUE TITLE
Email address required

### ISSUE THREAD

**Issue by Sachit71** [Jonathan357611/AvatarGenerator#2]
Hey there Jonathan, I'd like to know your e-mail address to discuss something related to this project. Thanks!

**Comment by Jonathan357611** [comment]
Hey There! You can reach me at dev.jonathan.fortmann@gmail.com !

**Comment by Sachit71** [comment]
Thanks Jonathan, I've sent the mail, please do reply at the earliest 😄

**Comment by Jonathan357611** [comment]
Sorry, but I didn't get anything. Are you sure you've sent it?

**Comment by Sachit71** [comment]
Oh yeah my bad one sec

**Comment by Sachit71** [comment]
Could you check now?

**Comment by Jonathan357611** [comment]
Perfect. I got it now!
