### ISSUE TITLE
me again, might've recognised my pfp from your project

### ISSUE THREAD

**Issue by therealcyber71** [Jonathan357611/AvatarGenerator#3]
check mail ;D i'll close the issue as soon as you reply to this

**Comment by therealcyber71** [comment]
hiya jonathan, please do check your mail!

**Comment by therealcyber71** [comment]
hiya, please check your mail :D

**Comment by Jonathan357611** [comment]
Just responded you per mail.

**Comment by therealcyber71** [comment]
sorry for checking this now lol, replied there, I will be closing this issue
